#!/usr/bin/env bash

cd /app

[ -f /etc/container_environment/JAVA_XMS ] && JAVA_XMS=$(cat /etc/container_environment/JAVA_XMS) || JAVA_XMS=20m
[ -f /etc/container_environment/JAVA_XMX ] && JAVA_XMX=$(cat /etc/container_environment/JAVA_XMX) || JAVA_XMX=512m
[ -f /etc/container_environment/JVM_OPTS ] && JVM_OPTS=$(cat /etc/container_environment/JVM_OPTS) || JVM_OPTS=""
[ -f /etc/container_environment/JAVA_OPTS ] && JAVA_OPTS=$(cat /etc/container_environment/JAVA_OPTS) || JAVA_OPTS=""
JAVA_OPTS=" -Xms${JAVA_XMS} -Xmx${JAVA_XMX} ${JVM_OPTS} ${JAVA_OPTS} "

exec java ${JAVA_OPTS} -jar dh2carbon.jar /app/config.properties
